fix: use relative trunk command

diff --git a/.github/workflows/build_and_deploy_to_pages.yml b/.github/workflows/build_and_deploy_to_pages.yml
--- a/.github/workflows/build_and_deploy_to_pages.yml
+++ b/.github/workflows/build_and_deploy_to_pages.yml
@@ -36,7 +36,9 @@ jobs:
       - name: Download and install Trunk binary
         run: wget -qO- https://github.com/trunk-rs/trunk/releases/download/v0.21.13/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
       - name: Build with Trunk
-        run: trunk build --release
+        run: ./trunk build --release
+      - name: Check dist exists
+        run: test -d dist || (echo "❌ dist/ folder not found!" && exit 1)
       - name: Upload static files as artifact
         id: deployment
         uses: actions/upload-pages-artifact@v3
